version: '3.8'

services:
  nginx:
    image: nginx:1.25
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    networks:
      - app
    depends_on:
      - app
    logging:
      driver: "fluentd"
      options:
        tag: nginx

  app:
    build: ./app
    command: >
      /bin/sh -c "python3 manage.py makemigrations
      && python3 manage.py migrate
      && python3 manage.py collectstatic --noinput
      && python3 manage.py createsuperuser --noinput --username $DJANGO_SUPERUSER_USERNAME --email $DJANGO_SUPERUSER_EMAIL
      ; gunicorn -w '2' --bind 0.0.0.0:8000 mymusic.wsgi:application"
    environment:
      - APP_ENVIRONMENT
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
    volumes:
      - static_volume:/mymusic/static
      - media_volume:/mymusic/media
    networks:
      - app
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: "fluentd"
      options:
        tag: app

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - app
    logging:
      driver: "fluentd"
      options:
        tag: db

  opensearch:
    image: opensearchproject/opensearch:2.15.0
    container_name: opensearch
    environment:
      - cluster.name=opensearch
      - node.name=opensearch
      - discovery.seed_hosts=opensearch
      - cluster.initial_cluster_manager_nodes=opensearch
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - logging
  
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.15.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
    networks:
      - logging

  fluentd:
    build: ./fluentd
    command: 'fluentd -c /fluentd/etc/fluentd.conf -v'
    ports:
      - 24224:24224
    expose:
      - "24224"
    volumes:
      - "./fluentd/fluentd.conf:/fluentd/etc/fluentd.conf"
    restart: "always"
    networks:
      - logging

networks:
  app:
    driver: bridge
  logging:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data:
  opensearch-data: