groups:
- name: Node
  rules:
  - alert: InstanceDown
    expr: up{job="Node"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Instance is down
      description: "Instance {{ $labels.instance }} is down."
  - alert: HighCpuUsage
    expr: sum by(instance)(irate(node_cpu_seconds_total{job="Node", mode="idle"}[5m])) * 100 < 10
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: High CPU usage detected
      description: "CPU usage on instance {{ $labels.instance }} has been above 90% for the last 5 minute."
  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes{job="Node"} - node_memory_MemAvailable_bytes{job="Node"}) / node_memory_MemTotal_bytes{job="Node"} > 0.9
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: High Memory Usage in {{ $labels.instance }}
      description: 'The {{ $labels.instance }} host is experiencing high memory usage.'
  - alert: HighStorageUsage
    expr: (node_filesystem_size_bytes{job="Node"}  - node_filesystem_free_bytes{job="Node"} ) / node_filesystem_size_bytes{job="Node"}  > 0.9
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: High Storage Usage on {{ $labels.instance }}
      description: 'The {{ $labels.instance }} host is experiencing high storage usage.'