global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093" 
rule_files:
  - alertrules.yml

scrape_configs:
- job_name: 'prometheus'
  static_configs:
    - targets: ['localhost:9090']
- job_name: 'alertmanager'
  static_configs:
    - targets: ['alertmanager:9093']
- job_name: 'grafana'
  static_configs:
    - targets: ['grafana:3000']
- job_name: 'node-exporter'
  file_sd_configs:
  - files:
    - 'targets.json'
- job_name: 'nginx'
  static_configs:
    - targets: ['nginx-prometheus-exporter:9113']