global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093" 
rule_files:
  - alertrules.yml

scrape_configs:
- job_name: 'prometheus'
  static_configs:
    - targets: ['prometheus:9090']
- job_name: 'alertmanager'
  static_configs:
    - targets: ['alertmanager:9093']
- job_name: 'grafana'
  static_configs:
    - targets: ['grafana:3000']
- job_name: 'node-exporter'
  file_sd_configs:
  - files:
    - 'targets.json'
- job_name: 'nginx'
  static_configs:
    - targets: ['host.docker.internal:9113']
- job_name: 'django'
  static_configs:
    - targets: ['host.docker.internal:80']
- job_name: 'postgres'
  static_configs:
    - targets: ['host.docker.internal:9187']
- job_name: 'blackbox_exporter'
  static_configs:
    - targets: ['blackbox:9115']
- job_name: 'blackbox'
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - http://host.docker.internal
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115