global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
route:
  receiver: default-receiver
  group_by:
  - alertname
  - job
  continue: false
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 15m
receivers:
- name: default-receiver